source 'https://rubygems.org'

gem 'rails', '3.2.8'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

gem 'sqlite3'


# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
	gem 'jquery-ui-rails'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
  
  gem 'bootstrap-sass'
  gem 'bourbon'
end

group :development, :test do
	gem 'factory_girl_rails', '~> 4.0'
	gem 'faker'
	gem 'nifty-generators'
	gem 'bcrypt-ruby', :require => 'bcrypt'
end

gem 'jquery-rails'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'
gem 'bcrypt-ruby', :require => 'bcrypt'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
gem 'capistrano'
gem 'rvm-capistrano'

# To use debugger
# gem 'debugger'

gem "mocha", :group => :test

gem 'google-api-client'

gem 'youtube_it',"2.1.8", :git => "git://github.com/kylejginavan/youtube_it.git"
gem 'chosen-rails'
gem 'simple_form'
gem 'omniauth-google-oauth2'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'css-social-buttons-rails'
gem 'will_paginate'
gem 'event-calendar', :require => "event_calendar"
gem "highcharts-rails", "~> 2.3.0"
gem "geocoder"
